config/routes.rb
Rails.application.routes.draw do
  resources :equipos

  resources :inventarios

  resources :clientes

  root 'inventarios#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	#has_many: equipos
	#has_many: inventarios
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
	#belongs_to: cliente
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
	#belongs_to :cliente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :ciudad, :telefono)
    end
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: [:show, :edit, :update, :destroy]

  # GET /equipos
  # GET /equipos.json
  def index
    @equipos = Equipo.all
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to @equipo, notice: 'Equipo was successfully created.' }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to @equipo, notice: 'Equipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipos_url, notice: 'Equipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipo_params
      params.require(:equipo).permit(:modelo, :fabricante, :funcion)
    end
end

app/controllers/inventarios_controller.rb
class InventariosController < ApplicationController
  before_action :set_inventario, only: [:show, :edit, :update, :destroy]

  # GET /inventarios
  # GET /inventarios.json
  def index
    @inventarios = Inventario.all
  end

  # GET /inventarios/1
  # GET /inventarios/1.json
  def show
  end

  # GET /inventarios/new
  def new
    @inventario = Inventario.new
  end

  # GET /inventarios/1/edit
  def edit
  end

  # POST /inventarios
  # POST /inventarios.json
  def create
    @inventario = Inventario.new(inventario_params)

    respond_to do |format|
      if @inventario.save
        format.html { redirect_to @inventario, notice: 'Inventario was successfully created.' }
        format.json { render :show, status: :created, location: @inventario }
      else
        format.html { render :new }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventarios/1
  # PATCH/PUT /inventarios/1.json
  def update
    respond_to do |format|
      if @inventario.update(inventario_params)
        format.html { redirect_to @inventario, notice: 'Inventario was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventario }
      else
        format.html { render :edit }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventarios/1
  # DELETE /inventarios/1.json
  def destroy
    @inventario.destroy
    respond_to do |format|
      format.html { redirect_to inventarios_url, notice: 'Inventario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario
      @inventario = Inventario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventario_params
      params.require(:inventario).permit(:pieza, :Disponible, :Usada, :Entrada)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "form-horizontal cliente" } do |f| %>

    <% if @cliente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <%= error_span(@cliente[:nombre]) %>
  </div>
  <div class="control-group">
    <%= f.label :ciudad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ciudad, :class => 'form-control' %>
    </div>
    <%= error_span(@cliente[:ciudad]) %>
  </div>
  <div class="control-group">
    <%= f.label :telefono, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefono, :class => 'form-control' %>
    </div>
    <%= error_span(@cliente[:telefono]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            clientes_path, :class => 'btn btn-default' %>

<% end %>

app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:ciudad) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to cliente.id, cliente_path(cliente) %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.ciudad %></td>
        <td><%= cliente.telefono %></td>
        <td><%=l cliente.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cliente_path(cliente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cliente_path(cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cliente_path,
            :class => 'btn btn-primary' %>

app/views/clientes/new.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @cliente.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ciudad) %>:</strong></dt>
  <dd><%= @cliente.ciudad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @cliente.telefono %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cliente_path(@cliente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cliente_path(@cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/equipos/_form.html.erb
<%= form_for(@equipo) do |f| %>
  <% if @equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipo.errors.count, "error") %> prohibited this equipo from being saved:</h2>

      <ul>
      <% @equipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :fabricante %><br>
    <%= f.text_field :fabricante %>
  </div>
  <div class="field">
    <%= f.label :funcion %><br>
    <%= f.text_field :funcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipos/edit.html.erb
<h1>Editing equipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipo %> |
<%= link_to 'Back', equipos_path %>

app/views/equipos/index.html.erb
<h1>Listing equipos</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Fabricante</th>
      <th>Funcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipos.each do |equipo| %>
      <tr>
        <td><%= equipo.modelo %></td>
        <td><%= equipo.fabricante %></td>
        <td><%= equipo.funcion %></td>
        <td><%= link_to 'Show', equipo %></td>
        <td><%= link_to 'Edit', edit_equipo_path(equipo) %></td>
        <td><%= link_to 'Destroy', equipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipo', new_equipo_path %>

app/views/equipos/new.html.erb
<h1>New equipo</h1>

<%= render 'form' %>

<%= link_to 'Back', equipos_path %>

app/views/equipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @equipo.modelo %>
</p>

<p>
  <strong>Fabricante:</strong>
  <%= @equipo.fabricante %>
</p>

<p>
  <strong>Funcion:</strong>
  <%= @equipo.funcion %>
</p>

<%= link_to 'Edit', edit_equipo_path(@equipo) %> |
<%= link_to 'Back', equipos_path %>

app/views/inventarios/_form.html.erb
<%= form_for @inventario, :html => { :class => "form-horizontal inventario" } do |f| %>

    <% if @inventario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@inventario.errors.count, "error") %> prohibited this inventario from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @inventario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :pieza, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pieza, :class => 'form-control' %>
    </div>
    <%= error_span(@inventario[:pieza]) %>
  </div>
  <div class="control-group">
    <%= f.label :Disponible, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Disponible, :class => 'form-control' %>
    </div>
    <%= error_span(@inventario[:Disponible]) %>
  </div>
  <div class="control-group">
    <%= f.label :Usada, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Usada, :class => 'form-control' %>
    </div>
    <%= error_span(@inventario[:Usada]) %>
  </div>
  <div class="control-group">
    <%= f.label :Entrada, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Entrada, :class => 'form-control' %>
    </div>
    <%= error_span(@inventario[:Entrada]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            inventarios_path, :class => 'btn btn-default' %>

<% end %>

app/views/inventarios/edit.html.erb
<%- model_class = Inventario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/inventarios/index.html.erb
<%- model_class = Inventario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pieza) %></th>
      <th><%= model_class.human_attribute_name(:Disponible) %></th>
      <th><%= model_class.human_attribute_name(:Usada) %></th>
      <th><%= model_class.human_attribute_name(:Entrada) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @inventarios.each do |inventario| %>
      <tr>
        <td><%= link_to inventario.id, inventario_path(inventario) %></td>
        <td><%= inventario.pieza %></td>
        <td><%= inventario.Disponible = (inventario.Entrada - inventario.Usada) %></td>
        <td><%= inventario.Usada %></td>
        <td><%= inventario.Entrada %></td>
        <td><%=l inventario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_inventario_path(inventario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      inventario_path(inventario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_inventario_path,
            :class => 'btn btn-primary' %>

app/views/inventarios/new.html.erb
<%- model_class = Inventario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/inventarios/show.html.erb
<%- model_class = Inventario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pieza) %>:</strong></dt>
  <dd><%= @inventario.pieza %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Disponible) %>:</strong></dt>
  <dd><%= @inventario.Disponible %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Usada) %>:</strong></dt>
  <dd><%= @inventario.Usada %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Entrada) %>:</strong></dt>
  <dd><%= @inventario.Entrada %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              inventarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_inventario_path(@inventario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              inventario_path(@inventario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Inventory Beta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-defaul" role="navigation">
      <div class="container">
        <%= link_to "Aqui pongo un logo o algo", '#', id: "logo" %>
        <nav>
          <ul class="nav nav-tabs">
            <li><%= link_to "Clientes",   clientes_path %></li>
            <li><%= link_to "Inventario",   inventarios_path %></li>
            <li><%= link_to "Equipo", equipos_path %></li>
          </ul>
        </nav>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/layouts/vista.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Appin" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Appin</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>